### ISSUE TITLE
GSMaP Data Download 오류

### ISSUE THREAD

**Issue by juhyeoh** [floodmodel/Converter#2]
**버그 내용**
Data Download 기능에서 GSMaP 데이터를 다운로드하려고 할 때, "No connection adapters were found for 'ftp://{id}:{pw}@hokusai.eorc.jaxa.jp/standard/v8/hourly/'" 오류 메시지 발생

**재현 과정**
1. Kict Satellite Precipitation Converter 플러그인에서 Data Download 선택
2. 'GPM', 'GSMaP', 'CMORPH' 중 'GSMaP' 선택
3. 해당 데이터 수집 웹사이트 계정의 ID/PW 입력, Start/End Date 입력 및 다운로드 될 파일의 경로 입력
4. 위 과정을 마친 후 OK 버튼 클릭
5. "No connection adapters were found for 'ftp://{id}:{pw}@hokusai.eorc.jaxa.jp/standard/v8/hourly/'" 오류 메시지 발생

**예상 정상 작동**
얻고자 하는 데이터가 설정한 파일의 경로에 있는 GSMaP 폴더 내에 올바르게 저장되는 것.

**참고 이미지**
![image](https://github.com/floodmodel/Converter/assets/158236860/93886a25-4f7d-457d-985b-cd6389c89d63)

**환경**
 - OS: Windows
 - Tool: Visual Studio Code
 - QGIS: 3.10.14 version

**Comment by minbert** [comment]
- 재현과정 4 에서 OK 버튼을 눌렀을 때 어떤 함수가 실행되는지 조사해보세요.
- 이 함수가 실행될 때 Requests를 사용하는지 ftplib를 사용하는지 조사해보세요.
- 만약 Requests가 사용될 경우 Requests에서 ftp를 지원하는지 알아보세요.

**Comment by juhyeoh** [comment]
- 재현과정 4 에서 OK 버튼을 눌렀을 때 어떤 함수가 실행되는지 조사해보세요.
  - btn_download_GSMap
  - self.btn_download_GSMap.clicked.connect(lambda:self.data_download("GSMAP"))
  - elif type == "GSMAP":
  - 위 elif문의 내부 구문 실행....

- 이 함수가 실행될 때 Requests를 사용하는지 ftplib를 사용하는지 조사해보세요.
  - GSMap_data_download 함수 내에서 사용하는 ftp_filename_get 함수  -> ftp 변수 선언 시 ftplib 사용.

- 만약 Requests가 사용될 경우 Requests에서 ftp를 지원하는지 알아보세요.
  - Requests는 네트워크 연결 여부를 확인할 때에만 사용 중.
  - Requests에서는 ftp에 대한 기본 지원을 제공하지 않음.
